services:
  client:
    build: ./client
    container_name: client
    ports:
      - "8080:80"
      - "4443:443"

    depends_on:
      - server
    restart: always
    networks:
      - app-network

  server:
    build: ./Server
    container_name: server
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@db:27017/mydatabase?authSource=admin
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
